sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang
  
env:
 - TRAVIS_BUILD_TYPE=Release
 - TRAVIS_BUILD_TYPE=Debug
 
install:
    - CI_DIR=$PWD
    - sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'
    - sudo apt-get update
    - sudo apt-get install -qq -y yarp icub --force-yes
    - sudo apt-get install -qq -y libeigen3-dev libboost-all-dev
    - cd ~
    - git clone https://github.com/ocra-recipes/eigen_lgsm.git
    - cd eigen_lgsm ; mkdir build ; cd build ; cmake ..
    - sudo make install
    - cd ~
    - git clone https://github.com/ocra-recipes/ocra-recipes.git
    - cd ocra-recipes; mkdir build ; cd build; cmake ..
    - make -j2
    - sudo make install
    - cd $CI_DIR
    - mkdir build ; cd build ; cmake ..  -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DNON_INTERACTIVE_BUILD:BOOL=TRUE
script:
    - make -j2
    - sudo make install
    #run tests
