title: OCRA
description: Optimization Based Control for Robotics Applications
logo: http://ocra-recipes.github.io/ocra-wbi-plugins/static/img/logoV3.svg
github: https://github.com/ocra-recipes/ocra-wbi-plugins
# about: SYROCO - SYstèmes RObotiques COmplexes
disqus_shortname: ocra
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: Source
      url: /doxygen/
      layout: doxygen
      icon: fa-github
    - text: Clients
      url: /clients/
      icon: fa-users
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Authors
      url: '/authors/'
      icon: fa-graduation-cap
    - text: About
      url: /about/
      icon: fa-comments
    # - text: XML Feed
    #   url: /feed.xml
    #   icon: fa-feed

social:
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://ocra-recipes.github.io/ocra-wbi-plugins"
baseurl: "/ocra-wbi-plugins"
paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
