title: O C R A
description: Optimiztion Based Control for Robotics Applications
author: OCRA
logo: http://ocra-recipes.github.io/ocra-wbi-plugins/static/img/logo-draft.png
github: https://github.com/ocra-recipes/ocra-wbi-plugins
about: Optimization Based Control for Robotics Applications
disqus_shortname: ocra
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/ocra-recipes/ocra-wbi-plugins
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

social:
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://aboutashu.com/hcz-jekyll-blog"
baseurl: "/hcz-jekyll-blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
